# Schema for configuration files of the Password Policy Length submodule.

password_policy.constraint.plugin.pwned_passwords:
  type: password_policy.constraint.plugin
  mapping:
    min_occurrences:
      type: integer
